#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os

from setuptools import find_namespace_packages, setup

# Define the source directories for each sub-package
PACKAGE_ROOTS = {
    "cli": "packages/cli/src",
    "common": "packages/common/src",
    "core": "packages/core/src",
    "media": "packages/media/src",
    "platforms": "packages/platforms/src",
}


def find_monorepo_packages():
    packages = []
    package_dir = {}

    for name, root in PACKAGE_ROOTS.items():
        if not os.path.exists(root):
            continue

        # Find all namespace packages in this root
        found = find_namespace_packages(where=root)
        packages.extend(found)

        for pkg in found:
            # Map the package name to its directory
            # e.g. 'agoras.cli' -> 'packages/cli/src/agoras/cli'
            path = pkg.replace(".", "/")
            package_dir[pkg] = os.path.join(root, path)

    return list(set(packages)), package_dir


packages, package_dir = find_monorepo_packages()

version = "2.1.1"

setup(
    name="agoras-meta",
    version=version,
    author="Luis Alejandro Martínez Faneyth",
    author_email="luis@luisalejandro.org",
    url="https://github.com/LuisAlejandro/agoras",
    description="Agoras Social Media Manager",
    long_description=open("README.rst").read() if os.path.exists("README.rst") else "",
    long_description_content_type="text/x-rst",
    # Package discovery
    packages=packages,
    package_dir=package_dir,
    # Ship non-Python data files (e.g. twitter-text weighted-length config).
    package_data={
        "agoras.core.text_limits": ["data/*.json"],
    },
    # Combined dependencies from all sub-packages (generated by scripts/sync_package_deps.py)
    install_requires=[
        # From agoras-common
        'requests==2.34.2',
        'beautifulsoup4==4.15.0',
        # From agoras-media
        'filetype==1.2.0',
        'opencv-python-headless==5.0.0.93',
        'Pillow>=12.3.0',
        # From agoras-core
        'atoma==0.0.17',
        'gspread==6.2.1',
        'google-auth==2.56.3',
        'python-dateutil==2.9.0.post0',
        # From agoras-platforms
        'tweepy==4.17.0',
        'python-facebook-api==0.24.0',
        'linkedin-api-client==0.3.0',
        'discord.py==2.7.1',
        'google-api-python-client==2.198.0',
        'google-api-core>=2.34.0',
        'google-auth-oauthlib>=1.4.0',
        'google-auth-httplib2==0.4.1',
        'oauth2client==4.1.3',
        'platformdirs==4.11.1',
        'authlib==1.7.2',
        'cryptography>=50.0.0',
        'python-telegram-bot>=22.1',
        # From agoras
        'PyYAML==6.0.3',
    ],

    # CLI Entry point
    entry_points={
        "console_scripts": [
            "agoras=agoras.cli.main:main",
        ],
    },
    python_requires=">=3.10",
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Programming Language :: Python :: 3.14",
    ],
)
