#!/usr/bin/env python3
"""Sync install_requires across Agoras packages and regenerate requirements.txt."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from packaging.requirements import Requirement
from packaging.version import Version

REPO_ROOT = Path(__file__).resolve().parent.parent
PACKAGES = ("common", "media", "core", "platforms", "cli")
INTERNAL_PREFIX = "agoras-"
PYPI_NAMES = {
    "common": "agoras-common",
    "media": "agoras-media",
    "core": "agoras-core",
    "platforms": "agoras-platforms",
    "cli": "agoras",
}
GENERATED_HEADER = "# Auto-generated from setup.py by scripts/sync_package_deps.py — do not edit.\n"
INSTALL_REQUIRES_BLOCK = re.compile(
    r"^[ \t]*(?:# Combined dependencies[^\n]*\n)?"
    r"^[ \t]*install_requires=\[\n"
    r"(?P<body>.*?)"
    r"^[ \t]*\],",
    re.MULTILINE | re.DOTALL,
)


def setup_path(package: str) -> Path:
    if package == "root":
        return REPO_ROOT / "setup.py"
    return REPO_ROOT / "packages" / package / "setup.py"


def requirements_path(package: str) -> Path:
    if package == "root":
        return REPO_ROOT / "requirements.txt"
    return REPO_ROOT / "packages" / package / "requirements.txt"


def read_version(content: str) -> str:
    match = re.search(r"^version = '([^']+)'", content, re.MULTILINE)
    if not match:
        raise ValueError("setup.py is missing version = ... assignment")
    return match.group(1)


def resolve_requirement_line(line: str, version: str) -> str:
    stripped = line.strip().rstrip(",")
    if not stripped or stripped.startswith("#"):
        raise ValueError(f"invalid requirement line: {line!r}")
    if stripped.startswith("f'") and stripped.endswith("'"):
        return stripped[2:-1].replace("{version}", version)
    if stripped.startswith('f"') and stripped.endswith('"'):
        return stripped[2:-1].replace("{version}", version)
    if stripped[0] in "'\"":
        return stripped.strip("'\"").split("#", 1)[0].strip()
    raise ValueError(f"unrecognized requirement line: {line!r}")


def extract_install_requires_body(content: str) -> str:
    match = INSTALL_REQUIRES_BLOCK.search(content)
    if not match:
        raise ValueError("install_requires block not found")
    return match.group("body")


def parse_install_requires(content: str) -> tuple[str, list[str]]:
    version = read_version(content)
    body = extract_install_requires_body(content)
    resolved = []
    for line in body.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        resolved.append(resolve_requirement_line(stripped, version))
    return version, resolved


def format_requirement_line(resolved: str) -> str:
    req = Requirement(resolved)
    if req.name.startswith(INTERNAL_PREFIX):
        return f"        f'{req.name}=={{version}}',"
    return f"        '{resolved}',"


def build_install_requires_block(
    resolved: list[str],
    *,
    root: bool = False,
    sections: list[tuple[str, list[str]]] | None = None,
) -> str:
    lines = []
    if root:
        lines.append("    # Combined dependencies from all sub-packages (generated by scripts/sync_package_deps.py)")
        lines.append("    install_requires=[")
        if sections:
            for label, section in sections:
                lines.append(f"        # From {label}")
                for req in section:
                    lines.append(f"        '{req}',")
        lines.append("    ],")
        return "\n".join(lines) + "\n"

    lines.append("    install_requires=[")
    for req in resolved:
        lines.append(format_requirement_line(req))
    lines.append("    ],")
    return "\n".join(lines) + "\n"


def replace_install_requires(content: str, new_block: str) -> str:
    match = INSTALL_REQUIRES_BLOCK.search(content)
    if not match:
        raise ValueError("install_requires block not found")
    tail = content[match.end() :].lstrip("\n")
    return content[: match.start()] + new_block.rstrip("\n") + "\n\n" + tail


def pick_highest(requirements: list[str]) -> str:
    reqs = [Requirement(item) for item in requirements]
    name = reqs[0].name
    exact_versions: list[Version] = []
    min_versions: list[Version] = []

    for req in reqs:
        for spec in req.specifier:
            if spec.operator == "==":
                exact_versions.append(Version(spec.version))
            elif spec.operator in (">=", ">"):
                min_versions.append(Version(spec.version))

    candidates = exact_versions + min_versions
    if not candidates:
        return requirements[0]

    highest = max(candidates)
    if exact_versions:
        return f"{name}=={highest}"
    return f"{name}>={highest}"


def specs_conflict(values: list[str]) -> bool:
    normalized = {str(Requirement(value).specifier) for value in values}
    return len(normalized) > 1


def reconcile_conflicts(
    package_requires: dict[str, list[str]],
) -> tuple[dict[str, list[str]], list[str]]:
    by_name: dict[str, list[tuple[str, str]]] = {}
    changes: list[str] = []

    for package in PACKAGES:
        for req in package_requires[package]:
            name = Requirement(req).name
            if name.startswith(INTERNAL_PREFIX):
                continue
            by_name.setdefault(name, []).append((package, req))

    canonical: dict[str, str] = {}
    for name, entries in by_name.items():
        values = [req for _, req in entries]
        if not specs_conflict(values):
            canonical[name] = values[0]
            continue
        winner = pick_highest(values)
        canonical[name] = winner
        changes.append(f"{name}: {', '.join(sorted(set(values)))} -> {winner}")

    updated = {package: [] for package in PACKAGES}
    for package in PACKAGES:
        for req in package_requires[package]:
            name = Requirement(req).name
            if name.startswith(INTERNAL_PREFIX):
                updated[package].append(req)
            else:
                updated[package].append(canonical[name])
    return updated, changes


def build_root_sections(
    package_requires: dict[str, list[str]],
) -> tuple[list[str], list[tuple[str, list[str]]]]:
    seen: set[str] = set()
    sections: list[tuple[str, list[str]]] = []
    flat: list[str] = []

    for package in PACKAGES:
        section: list[str] = []
        for req in package_requires[package]:
            name = Requirement(req).name
            if name.startswith(INTERNAL_PREFIX) or name in seen:
                continue
            seen.add(name)
            section.append(req)
            flat.append(req)
        if section:
            sections.append((PYPI_NAMES[package], section))
    return flat, sections


def write_if_changed(path: Path, content: str, check: bool = False) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    if not check:
        path.write_text(content, encoding="utf-8")
    return True


def write_requirements_txt(path: Path, resolved: list[str], check: bool = False) -> bool:
    content = GENERATED_HEADER + "\n".join(resolved) + "\n"
    return write_if_changed(path, content, check)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="report drift and exit 1 without writing any file",
    )
    check = parser.parse_args().check

    package_requires: dict[str, list[str]] = {}
    setup_contents: dict[str, str] = {}

    for package in PACKAGES:
        path = setup_path(package)
        content = path.read_text(encoding="utf-8")
        setup_contents[package] = content
        _, resolved = parse_install_requires(content)
        package_requires[package] = resolved

    package_requires, conflict_changes = reconcile_conflicts(package_requires)
    if conflict_changes:
        print("Reconciled dependency conflicts:")
        for change in conflict_changes:
            print(f"  - {change}")

    changed_files: list[str] = []

    for package in PACKAGES:
        path = setup_path(package)
        new_block = build_install_requires_block(package_requires[package])
        new_content = replace_install_requires(setup_contents[package], new_block)
        if write_if_changed(path, new_content, check):
            changed_files.append(str(path.relative_to(REPO_ROOT)))
        req_path = requirements_path(package)
        if write_requirements_txt(req_path, package_requires[package], check):
            changed_files.append(str(req_path.relative_to(REPO_ROOT)))

    root_flat, root_sections = build_root_sections(package_requires)
    root_content = setup_path("root").read_text(encoding="utf-8")
    root_block = build_install_requires_block(
        root_flat,
        root=True,
        sections=root_sections,
    )
    new_root_content = replace_install_requires(root_content, root_block)
    if write_if_changed(setup_path("root"), new_root_content, check):
        changed_files.append("setup.py")
    if write_requirements_txt(requirements_path("root"), root_flat, check):
        changed_files.append("requirements.txt")

    if not changed_files:
        print("All package dependencies are already in sync.")
        return 0

    print("Out of sync files:" if check else "Updated files:")
    for path in changed_files:
        print(f"  - {path}")
    if check:
        print("\nRun: python3 scripts/sync_package_deps.py")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
